### ISSUE TITLE
Is there a plan to support both Python 3 and others database ?

### ISSUE THREAD

**Issue by leeoo** [Paull/python-mysql-orm#2]
This is a cool framework!
Please add Python 3 support. Also please support Postgres, SQLite databases..
Thanks.

**Comment by Paull** [comment]
Hi, leeoo!
Thanks for your feedback!
but I'm so sorry that I'm not planning to change my working python to version 3 yet.
Also I don't use Postgres, SQLite, no environment  at all. so other databases won't be supported until someone else stand out.

**Comment by leeoo** [comment]
Thanks for your response.
May be I can try to add (or migrate to) Python 3 and Postgres/SQLite support by myself. If I do so, I will rename this project name, like drop 'mysql' from project name etc..
What licence is this project ? Or just following the CodeIgniter project with MIT..?

**Comment by Paull** [comment]
Yes, licence MIT. thanks for reminding:)
